---
services:
  bot:
    build: bot/
    environment:
      BOT_TOKEN: $BOT_TOKEN
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1m"
    restart: always
version: "3"
